version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - prometheus
      - grafana
      - maildev
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitoring_db
      SPRING_DATASOURCE_USERNAME: capellax
      SPRING_DATASOURCE_PASSWORD: 123456
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      SPRING_MAIL_HOST: maildev
      SPRING_MAIL_PORT: 1025

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capellax
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: monitoring_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  maildev:
    image: maildev/maildev
    container_name: maildev_container
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres_data:
