version: '3.8'
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: capellax
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: monitoring_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  maildev:
    image: maildev/maildev
    container_name: maildev_container
    restart: always
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  postgres_data:
