server:
  port: 8080

spring:
  application:
    name: monitoring-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring_db
    username: capellax
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
